# Generated by Django 4.2.7 on 2024-05-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('canceled', 'Canceled')], default='Pending', max_length=50),
        ),
    ]
