# Generated by Django 4.2.7 on 2024-05-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
